let fileBtn = document.querySelector(".file-btn")
let dropdownMenu = document.querySelector(".dropdown-menu")
let content = document.querySelector(".content")
let count = document.querySelector(".count").children
let boldBtn = document.querySelector(".bold-btn")
let underlineBtn = document.querySelector(".underline-btn")
let italicBtn = document.querySelector(".italic-btn")
let colorInput = document.querySelector(".color-input")
let newBtn = document.querySelector(".new-btn")
let savePdfBtn = document.querySelector(".save-pdf-btn")
let saveTxtBtn = document.querySelector(".save-txt-btn")

let isDropdownMenuOpen = false;
let contentValue = []
let isSelection = false;
let text = ""
var selection
var fileNameValue = document.querySelector(".file-name-input").value;

let handleMenu = function () {
    if (isDropdownMenuOpen === false) {
        dropdownMenu.style.translate = `0px 0px`
        isDropdownMenuOpen = true
        setTimeout(function() {
            dropdownMenu.style.zIndex = `999`
        }, 500)
    } else {
        dropdownMenu.style.translate = `0px -100px`
        isDropdownMenuOpen = false
        dropdownMenu.style.zIndex = `-999`
    }
}

fileBtn.addEventListener("click", handleMenu)

let handleContent = function () {

    text = content.innerText
    contentValue = text.split(" ")
    count[1].innerHTML = `Số từ: ${contentValue.length}`
    count[0].innerHTML = `Số ký tự: ${text.length}`
    if (text.length === 0) {
        count[1].innerHTML = `Số từ: 0`
    }
} 

let getSelection = function () {
    selection = window.getSelection();
}

let handleUnderlineBtn = function () {
    document.execCommand('underline');
};

let handleitalicBtn = function () {
    document.execCommand('italic');
};

let handleBoldBtn = function () {
    document.execCommand('bold');
};

let handleTextColor = function () {
    document.execCommand('foreColor', false, colorInput.value);
}

document.querySelector(".file-name-input").addEventListener("input", function () {
    fileNameValue = document.querySelector(".file-name-input").value
    console.log(fileName);
})
window.addEventListener("mouseup", getSelection)
content.addEventListener("input", handleContent)
boldBtn.addEventListener("click", handleBoldBtn)
italicBtn.addEventListener("click", handleitalicBtn)
underlineBtn.addEventListener("click", handleUnderlineBtn)
document.addEventListener("mouseup", handleTextColor)
newBtn.addEventListener("click", function () {
    content.innerText = ""
    console.log(`khim`);
})

function getOptions() {
    return {
        filename: fileNameValue,
        header: '<div style="text-align:center;">Page <span class="page"></span> of <span class="total"></span></div>',
        footer: '<div style="text-align:center;">Generated by my app on ' + new Date().toLocaleDateString() + '</div>'
    };
}

savePdfBtn.addEventListener("click", function () {
    let options = getOptions();
    console.log(options.filename);
    html2pdf().set(options).from(content.innerHTML).save();
})




saveTxtBtn.addEventListener("click", function () {
    let textContent = content.textContent;
    let blob = new Blob([textContent], { type: 'text/plain' });
    let url = URL.createObjectURL(blob);
    let a = document.createElement('a');
    a.href = url;
    a.download = `${fileNameValue}.txt`;
    a.click();
    URL.revokeObjectURL(url);
})


